name = "Hikari"
uuid = "5bffff3a-c737-40b6-ad9e-159c82e716ea"
authors = ["your-name"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
